// Extended Mock Data for ZMRA System

import { CompanyProfile, RegistrationApplication, Document, Notification } from './types';

// Company Profiles with Extended Information
export const companyProfiles: CompanyProfile[] = [
  {
    id: 'mfr001',
    name: 'Zambia Health Pharmaceuticals Ltd',
    country: 'Zambia',
    cityEmail: 'lusaka@zhp.zm',
    phone: '+260 211 285000',
    website: 'www.zhp.zm',
    licenseNumber: 'ZHP-2019-001',
    licenseExpiryDate: '2026-12-31',
    status: 'active',
    certifications: ['ISO 9001:2015', 'GMP', 'WHO-PQ'],
    companyType: 'Manufacturer',
    gmpCertificationStatus: 'certified',
    registeredMedicinesCount: 8,
    inspectionHistoryIds: ['insp001', 'insp008', 'insp015'],
    medicineIds: ['med001', 'med004', 'med007', 'med009', 'med016', 'med019', 'med025', 'med031'],
    contactPerson: 'Mr. Chanda Mweemba',
    address: '5 Roan Street, Kitwe, Zambia',
    registrationDate: '2019-03-15',
  },
  {
    id: 'mfr002',
    name: 'Continental Pharmaceuticals (Pty) Ltd',
    country: 'South Africa',
    cityEmail: 'info@contpharm.co.za',
    phone: '+27 11 372 7000',
    website: 'www.continentalpharm.co.za',
    licenseNumber: 'COP-2020-015',
    licenseExpiryDate: '2027-08-15',
    status: 'active',
    certifications: ['ISO 9001:2015', 'GMP', 'NMRPPP'],
    companyType: 'Manufacturer',
    gmpCertificationStatus: 'certified',
    registeredMedicinesCount: 10,
    inspectionHistoryIds: ['insp002', 'insp009', 'insp018'],
    medicineIds: ['med002', 'med005', 'med008', 'med011', 'med014', 'med021', 'med026', 'med032', 'med038', 'med044'],
    contactPerson: 'Dr. Thabo Nkosi',
    address: 'Corporate Park, Kempton Park, Johannesburg, South Africa',
    registrationDate: '2020-06-20',
  },
  {
    id: 'mfr003',
    name: 'East African Medicines Co',
    country: 'Kenya',
    cityEmail: 'nairobi@eamc.ke',
    phone: '+254 20 444 5678',
    website: 'www.eamedicines.ke',
    licenseNumber: 'EAMC-2018-042',
    licenseExpiryDate: '2025-10-30',
    status: 'active',
    certifications: ['ISO 9001:2015', 'GMP'],
    companyType: 'Importer',
    gmpCertificationStatus: 'certified',
    registeredMedicinesCount: 6,
    inspectionHistoryIds: ['insp003', 'insp010'],
    medicineIds: ['med012', 'med018', 'med024', 'med030', 'med036', 'med042'],
    contactPerson: 'Ms. Jane Kipchoge',
    address: 'Upper Hill, Nairobi, Kenya',
    registrationDate: '2018-11-10',
  },
  {
    id: 'mfr004',
    name: 'Novartis Pharma AG',
    country: 'Switzerland',
    cityEmail: 'afadmin@novartis.com',
    phone: '+41 61 696 1111',
    website: 'www.novartis.com',
    licenseNumber: 'NOV-2015-088',
    licenseExpiryDate: '2028-05-20',
    status: 'active',
    certifications: ['ISO 9001:2015', 'GMP', 'WHO-PQ'],
    companyType: 'Manufacturer',
    gmpCertificationStatus: 'certified',
    registeredMedicinesCount: 12,
    inspectionHistoryIds: ['insp004', 'insp011', 'insp019'],
    medicineIds: ['med003', 'med006', 'med010', 'med013', 'med017', 'med020', 'med023', 'med027', 'med033', 'med039', 'med045', 'med050'],
    contactPerson: 'Dr. Stefan Müller',
    address: 'Lightenstrasse 450, Basel 4056, Switzerland',
    registrationDate: '2015-09-01',
  },
  {
    id: 'mfr005',
    name: 'GlaxoSmithKline plc',
    country: 'United Kingdom',
    cityEmail: 'africa@gsk.com',
    phone: '+44 20 8047 4000',
    website: 'www.gsk.com',
    licenseNumber: 'GSK-2014-091',
    licenseExpiryDate: '2027-12-01',
    status: 'active',
    certifications: ['ISO 9001:2015', 'GMP', 'WHO-PQ'],
    companyType: 'Manufacturer',
    gmpCertificationStatus: 'certified',
    registeredMedicinesCount: 15,
    inspectionHistoryIds: ['insp005', 'insp012', 'insp020'],
    medicineIds: ['med015', 'med022', 'med028', 'med034', 'med040', 'med046', 'med051', 'med052', 'med053', 'med054', 'med055', 'med056', 'med057', 'med058', 'med059'],
    contactPerson: 'Mr. James Richardson',
    address: 'Brentford, Middlesex TW8 9GS, United Kingdom',
    registrationDate: '2014-05-20',
  },
  {
    id: 'mfr006',
    name: 'Pfizer Inc',
    country: 'United States',
    cityEmail: 'africa@pfizer.com',
    phone: '+1 212 733 2323',
    website: 'www.pfizer.com',
    licenseNumber: 'PFZ-2016-075',
    licenseExpiryDate: '2026-09-10',
    status: 'active',
    certifications: ['ISO 9001:2015', 'GMP', 'FDA'],
    companyType: 'Manufacturer',
    gmpCertificationStatus: 'certified',
    registeredMedicinesCount: 11,
    inspectionHistoryIds: ['insp006', 'insp013', 'insp021'],
    medicineIds: ['med010', 'med029', 'med035', 'med041', 'med047', 'med048', 'med049', 'med060', 'med061', 'med062', 'med063'],
    contactPerson: 'Dr. Robert Sullivan',
    address: '235 East 42nd Street, New York, USA',
    registrationDate: '2016-07-01',
  },
  {
    id: 'mfr007',
    name: 'Cipla Ltd',
    country: 'India',
    cityEmail: 'export@cipla.com',
    phone: '+91 22 6426 4444',
    website: 'www.cipla.com',
    licenseNumber: 'CIP-2017-063',
    licenseExpiryDate: '2025-11-25',
    status: 'active',
    certifications: ['ISO 9001:2015', 'GMP', 'WHO-PQ'],
    companyType: 'Manufacturer',
    gmpCertificationStatus: 'certified',
    registeredMedicinesCount: 9,
    inspectionHistoryIds: ['insp007', 'insp014'],
    medicineIds: ['med037', 'med043', 'med064', 'med065', 'med066', 'med067', 'med068', 'med069', 'med070'],
    contactPerson: 'Mr. Anil Sharma',
    address: 'Central Avenue, Dabolim, Mumbai, India',
    registrationDate: '2017-02-10',
  },
];

// Regulatory Applications (20 in different stages)
export const registrationApplications: RegistrationApplication[] = [
  {
    id: 'app001',
    applicationNumber: 'APP-2025-001',
    medicineName: 'Metformin Tablets',
    manufacturerId: 'mfr001',
    manufacturerName: 'Zambia Health Pharmaceuticals Ltd',
    submissionDate: '2024-12-01',
    assignedReviewer: 'Dr. Chileshe Banda',
    status: 'approved',
    stage: 5,
    documents: ['metformin-application.pdf', 'preclinical-data.pdf', 'clinical-trials.pdf'],
    reviewComments: [
      {
        id: 'rc001',
        stage: 1,
        reviewer: 'Dr. Chileshe Banda',
        comment: 'Application complete and properly formatted.',
        date: '2025-01-10',
        status: 'approved',
      },
      {
        id: 'rc002',
        stage: 2,
        reviewer: 'Dr. Chileshe Banda',
        comment: 'Technical screening passed. Proceeding to laboratory testing.',
        date: '2025-02-05',
        status: 'approved',
      },
    ],
    evaluationChecklist: [
      {
        category: 'Formulation',
        items: [
          { item: 'Stability data', status: 'passed' },
          { item: 'Bioavailability', status: 'passed' },
          { item: 'Dosage justification', status: 'passed' },
        ],
      },
      {
        category: 'Safety',
        items: [
          { item: 'Toxicology studies', status: 'passed' },
          { item: 'Impurity testing', status: 'passed' },
        ],
      },
    ],
    approvalDecision: {
      approved: true,
      decisionDate: '2025-03-10',
      approvedBy: 'Dr. Chileshe Banda',
      remarks: 'All requirements met. Approved for registration.',
    },
  },
  {
    id: 'app002',
    applicationNumber: 'APP-2025-002',
    medicineName: 'Lisinopril Tablets',
    manufacturerId: 'mfr004',
    manufacturerName: 'Novartis Pharma AG',
    submissionDate: '2025-01-15',
    assignedReviewer: 'Dr. Mweemba Chanda',
    status: 'evaluation-committee',
    stage: 4,
    documents: ['lisinopril-dossier.pdf', 'phase-2-trials.pdf', 'manufacturing-data.pdf'],
    reviewComments: [
      {
        id: 'rc003',
        stage: 1,
        reviewer: 'Dr. Mweemba Chanda',
        comment: 'Complete dossier received. Technical review initiated.',
        date: '2025-01-20',
        status: 'approved',
      },
      {
        id: 'rc004',
        stage: 3,
        reviewer: 'Prof. Helen Muleya',
        comment: 'Laboratory testing completed successfully.',
        date: '2025-02-28',
        status: 'approved',
      },
    ],
    evaluationChecklist: [
      {
        category: 'Quality',
        items: [
          { item: 'Pharmaceutical development', status: 'passed' },
          { item: 'Specifications', status: 'passed' },
          { item: 'Analytical procedures', status: 'passed' },
        ],
      },
    ],
  },
  {
    id: 'app003',
    applicationNumber: 'APP-2025-003',
    medicineName: 'Atorvastatin Tablets',
    manufacturerId: 'mfr002',
    manufacturerName: 'Continental Pharmaceuticals (Pty) Ltd',
    submissionDate: '2025-02-01',
    assignedReviewer: 'Dr. Nalubamba Kaposa',
    status: 'laboratory-testing',
    stage: 3,
    documents: ['atorvastatin-cmc.pdf', 'nonclinical-safety.pdf'],
    reviewComments: [
      {
        id: 'rc005',
        stage: 1,
        reviewer: 'Dr. Nalubamba Kaposa',
        comment: 'Initial review completed. Quality documentation satisfactory.',
        date: '2025-02-10',
        status: 'approved',
      },
      {
        id: 'rc006',
        stage: 2,
        reviewer: 'Dr. Chileshe Banda',
        comment: 'Referred to laboratory for batch analysis.',
        date: '2025-02-20',
        status: 'approved',
      },
    ],
    evaluationChecklist: [
      {
        category: 'Laboratory Testing',
        items: [
          { item: 'Dissolution testing', status: 'pending' },
          { item: 'Content uniformity', status: 'pending' },
          { item: 'Microbial limits', status: 'pending' },
        ],
      },
    ],
  },
  {
    id: 'app004',
    applicationNumber: 'APP-2025-004',
    medicineName: 'Omeprazole Capsules',
    manufacturerId: 'mfr005',
    manufacturerName: 'GlaxoSmithKline plc',
    submissionDate: '2025-01-10',
    assignedReviewer: 'Prof. Helen Muleya',
    status: 'technical-screening',
    stage: 2,
    documents: ['omeprazole-module2.pdf', 'module3-quality.pdf', 'module4-safety.pdf', 'module5-clinical.pdf'],
    reviewComments: [
      {
        id: 'rc007',
        stage: 1,
        reviewer: 'Prof. Helen Muleya',
        comment: 'Technical screening in progress. Requesting additional CMC data.',
        date: '2025-02-08',
        status: 'needs-clarification',
      },
    ],
    evaluationChecklist: [
      {
        category: 'CMC',
        items: [
          { item: 'Active pharmaceutical ingredient source', status: 'pending', remarks: 'Awaiting supplier information' },
          { item: 'Manufacturing process validation', status: 'pending' },
        ],
      },
    ],
  },
  {
    id: 'app005',
    applicationNumber: 'APP-2025-005',
    medicineName: 'Sertraline Tablets',
    manufacturerId: 'mfr006',
    manufacturerName: 'Pfizer Inc',
    submissionDate: '2025-02-15',
    assignedReviewer: 'Dr. Chileshe Banda',
    status: 'submitted',
    stage: 1,
    documents: ['sertraline-application.pdf'],
    reviewComments: [],
    evaluationChecklist: [
      {
        category: 'Documentation',
        items: [
          { item: 'Application form completeness', status: 'pending' },
          { item: 'Regulatory history', status: 'pending' },
        ],
      },
    ],
  },
  {
    id: 'app006',
    applicationNumber: 'APP-2025-006',
    medicineName: 'Ibuprofen Tablets',
    manufacturerId: 'mfr007',
    manufacturerName: 'Cipla Ltd',
    submissionDate: '2025-01-20',
    assignedReviewer: 'Dr. Mweemba Chanda',
    status: 'approved',
    stage: 5,
    documents: ['ibuprofen-dossier.pdf', 'clinical-efficacy.pdf'],
    reviewComments: [],
    evaluationChecklist: [],
    approvalDecision: {
      approved: true,
      decisionDate: '2025-03-05',
      approvedBy: 'Dr. Mweemba Chanda',
      remarks: 'Approved for registration with standard conditions.',
    },
  },
  {
    id: 'app007',
    applicationNumber: 'APP-2025-007',
    medicineName: 'Ciprofloxacin Tablets',
    manufacturerId: 'mfr001',
    manufacturerName: 'Zambia Health Pharmaceuticals Ltd',
    submissionDate: '2025-02-05',
    assignedReviewer: 'Dr. Nalubamba Kaposa',
    status: 'rejected',
    stage: 5,
    documents: ['ciprofloxacin-application.pdf'],
    reviewComments: [
      {
        id: 'rc008',
        stage: 2,
        reviewer: 'Dr. Nalubamba Kaposa',
        comment: 'Critical deficiencies identified in clinical data.',
        date: '2025-02-25',
        status: 'pending-revision',
      },
    ],
    evaluationChecklist: [],
    approvalDecision: {
      approved: false,
      decisionDate: '2025-03-01',
      approvedBy: 'Dr. Nalubamba Kaposa',
      remarks: 'Rejected due to insufficient clinical evidence and quality concerns.',
    },
  },
  {
    id: 'app008',
    applicationNumber: 'APP-2025-008',
    medicineName: 'Amlodipine Tablets',
    manufacturerId: 'mfr002',
    manufacturerName: 'Continental Pharmaceuticals (Pty) Ltd',
    submissionDate: '2025-02-10',
    assignedReviewer: 'Prof. Helen Muleya',
    status: 'laboratory-testing',
    stage: 3,
    documents: ['amlodipine-module2.pdf', 'stability-data.pdf'],
    reviewComments: [],
    evaluationChecklist: [],
  },
  {
    id: 'app009',
    applicationNumber: 'APP-2025-009',
    medicineName: 'Metoprolol Tablets',
    manufacturerId: 'mfr004',
    manufacturerName: 'Novartis Pharma AG',
    submissionDate: '2025-02-12',
    assignedReviewer: 'Dr. Chileshe Banda',
    status: 'technical-screening',
    stage: 2,
    documents: ['metoprolol-cmc.pdf'],
    reviewComments: [],
    evaluationChecklist: [],
  },
  {
    id: 'app010',
    applicationNumber: 'APP-2025-010',
    medicineName: 'Ranitidine Tablets',
    manufacturerId: 'mfr005',
    manufacturerName: 'GlaxoSmithKline plc',
    submissionDate: '2025-02-14',
    assignedReviewer: 'Dr. Mweemba Chanda',
    status: 'submitted',
    stage: 1,
    documents: ['ranitidine-application.pdf'],
    reviewComments: [],
    evaluationChecklist: [],
  },
];

// Documents (linked to various entities)
export const documents: Document[] = [
  {
    id: 'doc001',
    name: 'GMP Certificate - Zambia Health Pharma',
    type: 'gmp',
    linkedTo: {
      entityType: 'manufacturer',
      entityId: 'mfr001',
      entityName: 'Zambia Health Pharmaceuticals Ltd',
    },
    uploadDate: '2023-06-15',
    uploadedBy: 'ZMRA Inspector',
    fileUrl: '/documents/gmp-zhp-2023.pdf',
    fileSize: 2048576,
    mimeType: 'application/pdf',
    status: 'approved',
    expiryDate: '2026-06-15',
    version: 2,
  },
  {
    id: 'doc002',
    name: 'Certificate of Analysis - Metformin',
    type: 'analysis',
    linkedTo: {
      entityType: 'medicine',
      entityId: 'med003',
      entityName: 'Metformin Tablets',
    },
    uploadDate: '2025-02-20',
    uploadedBy: 'Laboratory',
    fileUrl: '/documents/coa-metformin-2025.pdf',
    fileSize: 1024000,
    mimeType: 'application/pdf',
    status: 'approved',
    version: 1,
  },
  {
    id: 'doc003',
    name: 'Inspection Report - Continental Pharma',
    type: 'inspection-report',
    linkedTo: {
      entityType: 'manufacturer',
      entityId: 'mfr002',
      entityName: 'Continental Pharmaceuticals (Pty) Ltd',
    },
    uploadDate: '2025-01-30',
    uploadedBy: 'Inspector Nkosi',
    fileUrl: '/documents/inspection-continental-2025.pdf',
    fileSize: 3145728,
    mimeType: 'application/pdf',
    status: 'approved',
    version: 1,
  },
  {
    id: 'doc004',
    name: 'Laboratory Test Report - Paracetamol',
    type: 'lab-report',
    linkedTo: {
      entityType: 'medicine',
      entityId: 'med001',
      entityName: 'Paracetamol Tablets',
    },
    uploadDate: '2025-02-25',
    uploadedBy: 'Lab Analyst',
    fileUrl: '/documents/lab-report-paracetamol-2025.pdf',
    fileSize: 2097152,
    mimeType: 'application/pdf',
    status: 'approved',
    version: 1,
  },
  {
    id: 'doc005',
    name: 'Quality Assurance Certificate - GSK',
    type: 'quality-assurance',
    linkedTo: {
      entityType: 'manufacturer',
      entityId: 'mfr005',
      entityName: 'GlaxoSmithKline plc',
    },
    uploadDate: '2024-12-01',
    uploadedBy: 'ZMRA QA Team',
    fileUrl: '/documents/qa-gsk-2024.pdf',
    fileSize: 1572864,
    mimeType: 'application/pdf',
    status: 'approved',
    version: 3,
  },
  {
    id: 'doc006',
    name: 'Approval Certificate - Paracetamol',
    type: 'approval',
    linkedTo: {
      entityType: 'medicine',
      entityId: 'med001',
      entityName: 'Paracetamol Tablets',
    },
    uploadDate: '2019-03-20',
    uploadedBy: 'Regulatory Affairs',
    fileUrl: '/documents/approval-paracetamol-2019.pdf',
    fileSize: 512000,
    mimeType: 'application/pdf',
    status: 'approved',
    version: 1,
  },
  {
    id: 'doc007',
    name: 'Application Dossier - Atorvastatin',
    type: 'certificate',
    linkedTo: {
      entityType: 'application',
      entityId: 'app003',
      entityName: 'Atorvastatin Tablets',
    },
    uploadDate: '2025-02-01',
    uploadedBy: 'Applicant',
    fileUrl: '/documents/atorvastatin-dossier-2025.pdf',
    fileSize: 5242880,
    mimeType: 'application/pdf',
    status: 'pending-approval',
    version: 1,
  },
];

// Notifications & Alerts
export const notifications: Notification[] = [
  {
    id: 'notif001',
    type: 'expiring-approval',
    title: 'Medicine Approval Expiring Soon',
    message: 'Paracetamol Tablets (med001) approval expires in 30 days',
    linkedEntity: {
      entityType: 'medicine',
      entityId: 'med001',
    },
    priority: 'high',
    date: '2026-03-14',
    isRead: false,
  },
  {
    id: 'notif002',
    type: 'expiring-batch',
    title: 'Batch Nearing Expiry',
    message: 'Batch MET-2025-001 (Metformin) expires on 2026-04-15',
    linkedEntity: {
      entityType: 'batch',
      entityId: 'batch001',
    },
    priority: 'medium',
    date: '2026-03-12',
    isRead: false,
  },
  {
    id: 'notif003',
    type: 'overdue-inspection',
    title: 'Overdue Manufacturer Inspection',
    message: 'Continental Pharmaceuticals inspection is 20 days overdue',
    linkedEntity: {
      entityType: 'manufacturer',
      entityId: 'mfr002',
    },
    priority: 'high',
    date: '2026-03-10',
    isRead: true,
  },
  {
    id: 'notif004',
    type: 'safety-recall',
    title: 'Safety Recall Issued',
    message: 'Class II recall issued for Enalapril Tablets batch EMP-2026-002',
    linkedEntity: {
      entityType: 'medicine',
      entityId: 'med006',
    },
    priority: 'critical',
    date: '2026-02-19',
    isRead: true,
  },
  {
    id: 'notif005',
    type: 'expiring-approval',
    title: 'Multiple Approvals Expiring',
    message: '5 medicines have approvals expiring within 90 days',
    linkedEntity: undefined,
    priority: 'high',
    date: '2026-03-14',
    isRead: false,
  },
  {
    id: 'notif006',
    type: 'system-alert',
    title: 'Application Review Pending',
    message: 'Lisinopril Tablets application (APP-2025-002) awaiting committee evaluation',
    linkedEntity: {
      entityType: 'medicine',
      entityId: 'med017',
    },
    priority: 'medium',
    date: '2026-03-08',
    isRead: false,
  },
  {
    id: 'notif007',
    type: 'expiring-batch',
    title: 'Warehouse Inventory Check',
    message: '12 batches will expire within 6 months',
    linkedEntity: undefined,
    priority: 'medium',
    date: '2026-03-07',
    isRead: true,
  },
  {
    id: 'notif008',
    type: 'safety-recall',
    title: 'Class I Recall Status',
    message: 'Paracetamol batch PAB-2026-002 recall completed successfully',
    linkedEntity: {
      entityType: 'medicine',
      entityId: 'med001',
    },
    priority: 'high',
    date: '2026-02-16',
    isRead: true,
  },
];
